DECLARE AGE: INTEGER
DECLARE NAME: STRING
DECLARE DAYS_OF_YEAR: REAL
DECLARE BEST_ALPHABET: CHAR

AGE <- 2024-2009
NAME <- "Minsu"
DAYS_OF_YEAR <- 365.2425
BEST_ALPHABET <- "A"

OUTPUT AGE, NAME, DAYS_OF_YEAR, BEST_ALPHABET
